name: milvik_flutter_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^2.1.0
  google_fonts: ^2.1.0
  pin_code_fields: ^7.3.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flushbar: ^1.10.4
  http: ^0.13.3
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4
  image_cropper: ^1.4.1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
